// Generated by CoffeeScript 1.8.0
var OverwriteError,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

OverwriteError = (function(_super) {
  __extends(OverwriteError, _super);

  function OverwriteError(obj, dec) {}

  return OverwriteError;

})(global.Error);

module.exports = OverwriteError;
